@ShiftsLoggerV2.RyanW84_HostAddress = https://localhost:7009/

GET {{ShiftsLoggerV2.RyanW84_HostAddress}}/api/shifts
Accept: application/json

###

GET {{ShiftsLoggerV2.RyanW84_HostAddress}}/api/workers?pageNumber=1&pageSize=10
Accept: application/json

###
